[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "poseai"
authors = [{name = "poseai", email = "info@poseai.co.uk"}]
dynamic = ["version", "description"]
